class_labels = [
    "Apple___Apple_scab", "Apple___Black_rot", "Apple___Cedar_apple_rust", "Apple___healthy",
    "Blueberry___healthy", "Cherry_(including_sour)___Powdery_mildew", "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot", "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight", "Corn_(maize)___healthy", "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)", "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)", "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)", "Peach___Bacterial_spot", "Peach___healthy",
    "Pepper,_bell___Bacterial_spot", "Pepper,_bell___healthy", "Potato___Early_blight",
    "Potato___Late_blight", "Potato___healthy", "Raspberry___healthy", "Soybean___healthy",
    "Squash___Powdery_mildew", "Strawberry___Leaf_scorch", "Strawberry___healthy",
    "Tomato___Bacterial_spot", "Tomato___Early_blight", "Tomato___Late_blight",
    "Tomato___Leaf_Mold", "Tomato___Septoria_leaf_spot", "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot", "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus", "Tomato___healthy"
]

treatment_suggestions = {
    "Apple___Apple_scab": "Remove infected leaves and apply fungicide.",
    "Apple___Black_rot": "Prune affected areas and use copper-based sprays.",
    "Apple___Cedar_apple_rust": "Use resistant varieties and fungicides.",
    "Apple___healthy": "No treatment needed.",
    "Blueberry___healthy": "No treatment needed.",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur-based fungicides.",
    "Cherry_(including_sour)___healthy": "No treatment needed.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Rotate crops and apply fungicide.",
    "Corn_(maize)___Common_rust_": "Use resistant hybrids and fungicides.",
    "Corn_(maize)___Northern_Leaf_Blight": "Use fungicides and rotate crops.",
    "Corn_(maize)___healthy": "No treatment needed.",
    "Grape___Black_rot": "Prune infected vines and apply fungicides.",
    "Grape___Esca_(Black_Measles)": "Remove infected vines and use balanced fertilization.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Use protective fungicide sprays.",
    "Grape___healthy": "No treatment needed.",
    "Orange___Haunglongbing_(Citrus_greening)": "Remove and destroy infected trees.",
    "Peach___Bacterial_spot": "Apply copper sprays and remove infected areas.",
    "Peach___healthy": "No treatment needed.",
    "Pepper,_bell___Bacterial_spot": "Use disease-free seeds and copper sprays.",
    "Pepper,_bell___healthy": "No treatment needed.",
    "Potato___Early_blight": "Apply chlorothalonil or mancozeb-based fungicides.",
    "Potato___Late_blight": "Use metalaxyl and remove infected plants.",
    "Potato___healthy": "No treatment needed.",
    "Raspberry___healthy": "No treatment needed.",
    "Soybean___healthy": "No treatment needed.",
    "Squash___Powdery_mildew": "Use neem oil or sulfur sprays.",
    "Strawberry___Leaf_scorch": "Remove infected leaves and apply fungicides.",
    "Strawberry___healthy": "No treatment needed.",
    "Tomato___Bacterial_spot": "Use resistant varieties and copper sprays.",
    "Tomato___Early_blight": "Apply fungicides like chlorothalonil.",
    "Tomato___Late_blight": "Use fungicides like mancozeb or copper sprays.",
    "Tomato___Leaf_Mold": "Ensure ventilation and apply fungicide.",
    "Tomato___Septoria_leaf_spot": "Remove lower leaves and use fungicides.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use insecticidal soap or neem oil.",
    "Tomato___Target_Spot": "Apply strobilurin-based fungicides.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Use resistant varieties and control whiteflies.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants and sanitize tools.",
    "Tomato___healthy": "No treatment needed."
}